In [2]:
# !pip install river
from river import drift
from river import stream
from river import metrics
from river import tree
from river import ensemble
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
## read dasets 
df_sudden_dos = pd.read_csv("/home/jovyan/data/df_sudden_dos.csv", sep = ";")
df_sudden_ftp = pd.read_csv("/home/jovyan/data/df_sudden_ftp.csv", sep = ";")
df_sudden_web = pd.read_csv("/home/jovyan/data/df_sudden_web.csv", sep = ";")
df_sudden_rec_dos = pd.read_csv("/home/jovyan/data/df_sudden_rec_dos.csv", sep = ";")
df_sudden_rec_ftp = pd.read_csv("/home/jovyan/data/df_sudden_rec_ftp.csv", sep = ";")
df_sudden_rec_web = pd.read_csv("/home/jovyan/data/df_sudden_rec_web.csv", sep = ";")
df_gradual_dos = pd.read_csv("/home/jovyan/data/df_gradual_dos.csv", sep = ";")
df_gradual_ftp = pd.read_csv("/home/jovyan/data/df_gradual_ftp.csv", sep = ";")
df_gradual_web = pd.read_csv("/home/jovyan/data/df_gradual_web.csv", sep = ";")

df_slice_dos = pd.read_csv("/home/jovyan/data/df_attact_dos_slice.csv", sep = ";")
df_slice_ftp = pd.read_csv("/home/jovyan/data/df_attact_ftp_slice.csv", sep = ";")
df_slice_web = pd.read_csv("/home/jovyan/data/df_attact_web_slice.csv", sep = ";")

In [6]:
len(df_sudden_dos.columns)

64

In [3]:
def ABC(X, y, window = 100):
    model = ensemble.ADWINBoostingClassifier(
        model=tree.HoeffdingAdaptiveTreeClassifier(
            grace_period=50,
            delta=1e-5,
            leaf_prediction='nb',
            nb_threshold=10,
            seed=0
        ),
        n_models=30,
        seed=42
    )
    Y_pred = list()
    metric = metrics.F1()
    for xi, yi in stream.iter_pandas(X, y):
        # Test the current model on the new "unobserved" sample
        yi_pred = model.predict_one(xi)
        # Update the running metric with the prediction and ground truth value
        metric.update(yi, yi_pred)  
        # Train the model with the new sample
        model.learn_one(xi, yi)
        Y_pred.append(yi_pred)
    return(Y_pred)

## df_sudden_dos

In [ ]:
y = 1 - pd.get_dummies(df_sudden_dos.label, drop_first= True, dtype=int).benign
X = df_sudden_dos.drop(columns="label")

In [ ]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_sudden_dos_ABC_predict.csv",index= False, sep = ";")

## df_sudden_ftp

In [ ]:
df = df_sudden_ftp
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [ ]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_sudden_ftp_ABC_predict.csv",index= False, sep = ";")

## df_sudden_web

In [ ]:
df = df_sudden_web
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [ ]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_sudden_web_ABC_predict.csv",index= False, sep = ";")

## df_sudden_rec_dos

In [ ]:
df = df_sudden_rec_dos
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [ ]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_sudden_rec_ABC_dos.csv",index= False, sep = ";")

## df_sudden_rec_ftp

In [ ]:
df = df_sudden_rec_ftp
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [ ]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_sudden_rec_ABC_ftp.csv",index= False, sep = ";")

## df_sudden_rec_web

In [ ]:
df = df_sudden_rec_web
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [ ]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_sudden_rec_ABC_web.csv",index= False, sep = ";")

## df_gradual_dos

In [ ]:
df = df_gradual_dos
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [ ]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_gradual_dos_ABC.csv",index= False, sep = ";")

## df_gradual_ftp

In [ ]:
df = df_gradual_ftp
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [ ]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_gradual_ftp_ABC.csv",index= False, sep = ";")

## df_gradual_web

In [ ]:
df = df_gradual_web
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [ ]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_gradual_web_ABC.csv",index= False, sep = ";")

# Slices

## df_slice_dos

In [4]:
df = df_slice_dos
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [5]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_slice_dos_ABC_predict_test.csv",index= False, sep = ";")

## df_slice_ftp

In [6]:
df = df_slice_ftp
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [7]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_slice_ftp_ABC_predict_test.csv",index= False, sep = ";")

## df_slice_web

In [8]:
df = df_slice_web
y = 1 - pd.get_dummies(df.label, drop_first= True, dtype=int).benign
X = df.drop(columns="label")

In [9]:
Y_pred = ABC(X, y)
df = pd.DataFrame(list(zip(y, Y_pred)), columns =['y', 'y_pred'])
df.to_csv("df_slice_web_ABC_predict_test.csv",index= False, sep = ";")

In [13]:
df_slice_dos.label = 1 - pd.get_dummies(df_slice_dos.label, drop_first= True, dtype=int).benign

In [16]:
import arff
arff.dump('/home/jovyan/data/df_slice_dos.arff'
      , df_slice_dos.values
      , relation='relation name'
      , names=df_slice_dos.columns)

,bidirectional_first_seen_ms,bidirectional_last_seen_ms,bidirectional_duration_ms,bidirectional_packets,bidirectional_bytes,src2dst_first_seen_ms,src2dst_last_seen_ms,src2dst_duration_ms,src2dst_packets,src2dst_bytes,...,src2dst_fin_packets,dst2src_syn_packets,dst2src_cwr_packets,dst2src_ece_packets,dst2src_urg_packets,dst2src_ack_packets,dst2src_psh_packets,dst2src_rst_packets,dst2src_fin_packets,label
0,1499260529836,1499260577290,47454,753,765812,1499260529836,1499260577275,47439,282,18746,...,1,1,0,0,0,471,5,0,1,0
1,1499260529855,1499260577244,47389,47,28618,1499260529855,1499260577229,47374,20,1943,...,1,1,0,0,0,27,2,0,1,0
2,1499260529869,1499260577290,47421,323,359376,1499260529869,1499260577274,47405,126,9142,...,1,1,0,0,0,197,8,0,1,0
3,1499260529873,1499260529873,0,4,524,1499260529873,1499260529873,0,2,182,...,0,0,0,0,0,0,0,0,0,0
4,1499260529873,1499260529935,62,6,826,1499260529873,1499260529915,42,4,364,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df_slice_dos.groupby("label").count()

,bidirectional_first_seen_ms,bidirectional_last_seen_ms,bidirectional_duration_ms,bidirectional_packets,bidirectional_bytes,src2dst_first_seen_ms,src2dst_last_seen_ms,src2dst_duration_ms,src2dst_packets,src2dst_bytes,...,src2dst_rst_packets,src2dst_fin_packets,dst2src_syn_packets,dst2src_cwr_packets,dst2src_ece_packets,dst2src_urg_packets,dst2src_ack_packets,dst2src_psh_packets,dst2src_rst_packets,dst2src_fin_packets
label,,,,,,,,,,,,,,,,,,,,,
0,43749,43749,43749,43749,43749,43749,43749,43749,43749,43749,...,43749,43749,43749,43749,43749,43749,43749,43749,43749,43749
1,14080,14080,14080,14080,14080,14080,14080,14080,14080,14080,...,14080,14080,14080,14080,14080,14080,14080,14080,14080,14080